name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - 3.8
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable caching
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.9"

      - name: Set up Python ${{ matrix.python_version }}
        run: uv python install ${{ matrix.python_version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests